const PRODUCTS=[
{id:'atlas-blend',name:'Atlas Coffee Blend',category:'coffee',sub:'Coffee Blends',format:'Ground',weight:'250 g',flavour:'Cocoa',roast:'Medium',price:145,badge:'Best Seller',image:'coffee-one',description:'Balanced, velvety and aromatic.',available:true,newest:4,best:10},
{id:'medina-espresso',name:'Medina Espresso',category:'coffee',sub:'Espresso',format:'Beans',weight:'500 g',flavour:'Cocoa',roast:'Dark',price:155,badge:'Best Seller',image:'coffee-two',description:'Deep roast with cocoa notes.',available:true,newest:3,best:9},
{id:'atlas-origin',name:'High Atlas Origin',category:'coffee',sub:'Single Origin',format:'Beans',weight:'250 g',flavour:'Floral',roast:'Light',price:175,badge:'New',image:'coffee-three',description:'Bright, floral and refined.',available:true,newest:10,best:6},
{id:'orange-coffee',name:'Orange Blossom Coffee',category:'coffee',sub:'Flavoured Coffee',format:'Ground',weight:'250 g',flavour:'Orange',roast:'Medium',price:165,badge:'Limited Edition',image:'coffee-one',description:'Warm coffee lifted by orange blossom.',available:true,newest:9,best:5},
{id:'mint-tea',name:'Moroccan Mint Tea',category:'tea',sub:'Moroccan Mint Tea',format:'Loose Leaf',weight:'120 g',flavour:'Mint',roast:'',price:120,badge:'Best Seller',image:'tea-one',description:'Fresh mint and elegant green tea.',available:true,newest:5,best:10},
{id:'green-jasmine',name:'Jasmine Green Tea',category:'tea',sub:'Green Tea',format:'Loose Leaf',weight:'100 g',flavour:'Jasmine',roast:'',price:135,badge:'New',image:'tea-two',description:'Delicate green tea with jasmine.',available:true,newest:10,best:7},
{id:'orange-tea',name:'Marrakech Orange Tea',category:'tea',sub:'Orange Tea',format:'Tea Bags',weight:'20 bags',flavour:'Orange',roast:'',price:110,badge:'',image:'tea-one',description:'Citrus brightness with Moroccan spice.',available:true,newest:7,best:6},
{id:'medina-chocolate',name:'Medina Chocolate Box',category:'chocolate',sub:'Assorted Boxes',format:'Gift Box',weight:'24 pcs',flavour:'Cocoa',roast:'',price:290,badge:'Gift',image:'chocolate-one',description:'A refined assortment of chocolates.',available:true,newest:6,best:9},
{id:'dark-bar',name:'70% Dark Chocolate Bar',category:'chocolate',sub:'Dark Chocolate',format:'Bar',weight:'100 g',flavour:'Cocoa',roast:'',price:85,badge:'',image:'chocolate-one',description:'Intense cocoa with a clean finish.',available:true,newest:4,best:7},
{id:'medjool',name:'Majhoul Date Selection',category:'dates',sub:'Medjool Dates',format:'Gift Box',weight:'500 g',flavour:'Natural',roast:'',price:210,badge:'Premium',image:'dates-one',description:'Generous dates in an elegant box.',available:true,newest:5,best:8},
{id:'stuffed-dates',name:'Almond Stuffed Dates',category:'dates',sub:'Stuffed Dates',format:'Gift Box',weight:'16 pcs',flavour:'Almond',roast:'',price:240,badge:'Gift',image:'dates-one',description:'Majhoul dates filled with almonds.',available:true,newest:8,best:7},
{id:'orange-honey',name:'Orange Blossom Honey',category:'honey',sub:'Orange Blossom Honey',format:'Jar',weight:'250 g',flavour:'Orange',roast:'',price:130,badge:'',image:'honey-one',description:'Fragrant Moroccan orange blossom honey.',available:true,newest:6,best:8},
{id:'atlas-honey',name:'Atlas Mountain Honey',category:'honey',sub:'Atlas Mountain Honey',format:'Jar',weight:'500 g',flavour:'Herbal',roast:'',price:195,badge:'Premium',image:'honey-one',description:'Rich mountain honey with herbal depth.',available:false,newest:3,best:6},
{id:'discovery-box',name:'Marrakech Discovery Box',category:'gifts',sub:'Luxury Hampers',format:'Gift Box',weight:'8 items',flavour:'Assorted',roast:'',price:490,badge:'Signature',image:'gifts-one',description:'Coffee, tea, chocolate and dates.',available:true,newest:8,best:10},
{id:'executive-case',name:'Executive Gift Case',category:'gifts',sub:'Corporate Gifts',format:'Gift Box',weight:'12 items',flavour:'Assorted',roast:'',price:690,badge:'Corporate',image:'gifts-two',description:'A premium presentation for business gifting.',available:true,newest:7,best:8}
];
const pageCategory=document.body.dataset.category||'all';
const grid=document.querySelector('.catalog-grid');
const count=document.querySelector('.product-count');
const empty=document.querySelector('.empty-state');
const searchInput=document.querySelector('#catalog-search');
const sortSelect=document.querySelector('#catalog-sort');
const filterButtons=[...document.querySelectorAll('[data-filter]')];
const subSelect=document.querySelector('#subcategory-filter');
const formatSelect=document.querySelector('#format-filter');
const flavourSelect=document.querySelector('#flavour-filter');
const roastSelect=document.querySelector('#roast-filter');
const availabilitySelect=document.querySelector('#availability-filter');
let activeCategory=pageCategory;
function money(value){return `${value} MAD`}
function card(p){return `<article class="catalog-card"><a href="product.html?id=${p.id}"><div class="catalog-image ${p.image}">${p.badge?`<span>${p.badge}</span>`:''}</div><h3>${p.name}</h3><p>${p.category} · ${p.sub}<br>${p.description}</p><strong>${money(p.price)}</strong></a><div class="catalog-card-actions"><a href="product.html?id=${p.id}">View product</a><button class="add-to-cart" data-product="${p.name}" data-id="${p.id}">Add to bag</button></div></article>`}
function optionValues(key,items){return [...new Set(items.map(p=>p[key]).filter(Boolean))].sort()}
function fillSelect(select,key,label,items){if(!select)return;select.innerHTML=`<option value="all">All ${label}</option>`+optionValues(key,items).map(v=>`<option value="${v}">${v}</option>`).join('')}
function baseItems(){return PRODUCTS.filter(p=>pageCategory==='all'||p.category===pageCategory)}
function setupFilters(){const items=baseItems();fillSelect(subSelect,'sub','subcategories',items);fillSelect(formatSelect,'format','formats',items);fillSelect(flavourSelect,'flavour','flavours',items);fillSelect(roastSelect,'roast','roasts',items)}
function render(){if(!grid)return;let items=PRODUCTS.filter(p=>activeCategory==='all'||p.category===activeCategory);const q=(searchInput?.value||'').toLowerCase();if(q)items=items.filter(p=>`${p.name} ${p.sub} ${p.description}`.toLowerCase().includes(q));[['sub',subSelect],['format',formatSelect],['flavour',flavourSelect],['roast',roastSelect]].forEach(([key,el])=>{if(el&&el.value!=='all')items=items.filter(p=>p[key]===el.value)});if(availabilitySelect?.value==='available')items=items.filter(p=>p.available);const sort=sortSelect?.value||'featured';if(sort==='price-asc')items.sort((a,b)=>a.price-b.price);if(sort==='price-desc')items.sort((a,b)=>b.price-a.price);if(sort==='newest')items.sort((a,b)=>b.newest-a.newest);if(sort==='best')items.sort((a,b)=>b.best-a.best);if(sort==='name')items.sort((a,b)=>a.name.localeCompare(b.name));grid.innerHTML=items.map(card).join('');if(count)count.textContent=`${items.length} products`;empty?.classList.toggle('visible',items.length===0);bindCartButtons()}
filterButtons.forEach(btn=>btn.addEventListener('click',()=>{activeCategory=btn.dataset.filter;filterButtons.forEach(b=>b.classList.toggle('active',b===btn));render()}));[searchInput,sortSelect,subSelect,formatSelect,flavourSelect,roastSelect,availabilitySelect].forEach(el=>el?.addEventListener('input',render));
document.querySelector('.mobile-filter-toggle')?.addEventListener('click',()=>document.querySelector('.catalog-sidebar')?.classList.toggle('open'));
function getCart(){try{return JSON.parse(localStorage.getItem('mff-cart')||'[]')}catch{return []}}
function saveCart(cart){localStorage.setItem('mff-cart',JSON.stringify(cart));document.querySelectorAll('.cart-count').forEach(el=>el.textContent=String(cart.reduce((n,i)=>n+i.qty,0)))}
function bindCartButtons(){document.querySelectorAll('.add-to-cart').forEach(button=>button.onclick=()=>{const id=button.dataset.id||button.dataset.product;const cart=getCart();const found=cart.find(i=>i.id===id);if(found)found.qty+=1;else cart.push({id,name:button.dataset.product,qty:1});saveCart(cart);window.dispatchEvent(new CustomEvent('mff-toast',{detail:`${button.dataset.product} added to your bag.`}))})}
setupFilters();render();saveCart(getCart());
const params=new URLSearchParams(location.search);if(document.body.classList.contains('product-page')){const product=PRODUCTS.find(p=>p.id===params.get('id'))||PRODUCTS[0];document.querySelector('[data-product-title]').textContent=product.name;document.querySelector('[data-product-price]').textContent=money(product.price);document.querySelector('[data-product-description]').textContent=product.description;document.querySelector('[data-product-category]').textContent=product.sub;document.querySelector('[data-product-availability]').textContent=product.available?'In stock':'Currently unavailable';document.querySelector('.product-gallery-main').className=`product-gallery-main ${product.image}`;const add=document.querySelector('.product-page .add-to-cart');if(add){add.dataset.id=product.id;add.dataset.product=product.name;add.disabled=!product.available}bindCartButtons()}